## NumPy - Numerical python

#### Hands on NumPy in Python

* Numpy is the most important library in python
  which is used in several domains like machine learning ,Data Science etc.
* Numpy is basically used for numerical operations


Advantages of NumPy Arrays
1. Allows several Mathematical operations
2. Faster operations

In [1]:
import numpy as np

###### List Vs. Numpy- Time Taken

In [2]:
from time import process_time

Time Taken by a List

In [17]:
python_list = [ i for i in range(10000)]
start_time = process_time()
python_list = [ i +5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0


In [19]:
np_array=np.array([i for i in range(10000)])
start_time = process_time()
np_array +=5
end_time = process_time()
print(end_time - start_time)

0.0


Numpy Array

In [20]:
# List example 
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In case of list elements are separated by comma and datatype is list

In [21]:
# Example of numpy array
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In case of numpy array elements are separated by space and datatype is numpy.ndarray
here ndarray - nd represents n dimension array

Arrays are similar to matrix which consist of rows and columns

#### Creating a 1 dimension array

In [22]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [23]:
a.shape

(4,)

In [24]:
# 2 dimension array
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


It is similar to 2x4 matrix that contain 2 rows & 4 columns

In [25]:
b.shape

(2, 4)

here 2 is no of rows and 4 is no. of columns - by default value is integer type

In [26]:
# Example - 3
c= np.array([(1,2,3,4),(5,6,7,8)], dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [27]:
d= np.array([(1.3,2,3,4),(5.6,6,7,8)])
print(d)

[[1.3 2.  3.  4. ]
 [5.6 6.  7.  8. ]]


Initial Placeholder in numpy arrays


In [29]:
# creating a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [30]:
# Creating a numpy array of ones.
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [31]:
# Array of a particular value
z= np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [32]:
# Creating an identity matrix = > no of rows and columns should be equal
a=np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [33]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [34]:
# Creating a numpy arraywith random values
b=np.random.random((3,4))
print(b)

[[0.94191302 0.1693536  0.99632725 0.3480471 ]
 [0.0255178  0.2971465  0.95162363 0.51994407]
 [0.14579563 0.32089924 0.13193654 0.72441206]]


Note : the values are between 0 & 1 whenever you run the values get change again
    between 0& 1

In [35]:
# random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[91 56 83 76 27]
 [69 76 81 88 45]
 [31 81 66 15 77]]


In [37]:
# array of evenly spaced values -->specifying the number of values required
d=np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [38]:
d=np.linspace(10,30,6)
print(d)

[10. 14. 18. 22. 26. 30.]


In [40]:
# array of evenly spaced values -->specifying the step
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [43]:
# Convert a list to a numpy array
list2 = [10,20,20,30,40]
np_array=np.asarray(list2)
print(np_array)
type(np_array)


[10 20 20 30 40]


numpy.ndarray

In [44]:
np_array.shape

(5,)

#### Analysing a numpy array

In [46]:
c=np.random.randint(10,90,(5,5))
print(c)

[[71 79 63 17 28]
 [81 21 62 71 18]
 [52 67 28 16 37]
 [17 10 47 78 44]
 [44 53 38 78 73]]


In [47]:
# array dimension
print(c.shape)

(5, 5)


In [50]:
# number of dimensions
print(c.ndim) # 2d array

2


In [51]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [52]:
print(a.ndim) # 1d array

1


In [53]:
# number of elements in an array
print(c.size)

25


In [54]:
# checking  the datatype of the values in an array
print(c.dtype)

int32


#### Mathematical Operations on a np array


In [55]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1 + list2)  # concatenate (or) joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [56]:
#using numpy array

a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [57]:
print(a)

[[1 8 4]
 [0 4 8]
 [5 9 0]]


In [58]:
print(b)

[[10 19 19]
 [18 10 17]
 [10 16 10]]


In [59]:
print(a + b)   # element wise addition ,subtraction ..

[[11 27 23]
 [18 14 25]
 [15 25 10]]


In [60]:
print(a-b)
print(a*b)
print(a/b)

[[ -9 -11 -15]
 [-18  -6  -9]
 [ -5  -7 -10]]
[[ 10 152  76]
 [  0  40 136]
 [ 50 144   0]]
[[0.1        0.42105263 0.21052632]
 [0.         0.4        0.47058824]
 [0.5        0.5625     0.        ]]


In [61]:
#Another way of doing this

a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))


In [62]:
print(a)
print(b)

[[6 5 4]
 [9 1 8]
 [8 5 3]]
[[15 17 13]
 [14 11 19]
 [15 11 17]]


In [63]:
print(np.add(a,b))

[[21 22 17]
 [23 12 27]
 [23 16 20]]


In [64]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ -9 -12  -9]
 [ -5 -10 -11]
 [ -7  -6 -14]]
[[ 90  85  52]
 [126  11 152]
 [120  55  51]]
[[0.4        0.29411765 0.30769231]
 [0.64285714 0.09090909 0.42105263]
 [0.53333333 0.45454545 0.17647059]]


#### Array Manipulation

In [65]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 1 0]
 [6 6 6]]
(2, 3)


In [66]:
# transpose of matrix
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 6]
 [1 6]
 [0 6]]
(3, 2)


In [67]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[9 4 3]
 [6 0 4]]
(2, 3)


In [68]:
# another way to do
trans2 = array.T
print(trans2)
print(trans2.shape)

[[9 6]
 [4 0]
 [3 4]]
(3, 2)


In [69]:
# Reshaping a array
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 3]
 [4 7 5]]
(2, 3)


In [70]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [3 4]
 [7 5]]
(3, 2)
