<a href="https://colab.research.google.com/github/SyedImranML/Machine-Learning/blob/main/5_2_Working_with_Matrix_in_Python_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

5.2 Working with Matrix in Python | Mathematics for Machine Learning | Linear Algebra

In [1]:
import numpy as np

Creating a Matrix using numpy

In [2]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [3]:
matrix_1.shape

(2, 2)

In [4]:
matrix_2 = np.array([[10,35,45],[50,64,80],[20,15,90]])
print(matrix_2)

[[10 35 45]
 [50 64 80]
 [20 15 90]]


In [5]:
matrix_2.shape

(3, 3)

Creating Matrices with Random Values

In [6]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.255351   0.49525738 0.49703286]
 [0.4115436  0.95626915 0.73032366]
 [0.28761078 0.02618014 0.15613798]]


In [7]:
# creating matrix with random integers
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[58 56 97 90 43]
 [58 12 15 35 26]
 [98 69 83 22 82]
 [87 23 31 78 18]]


Matrix with all the values as 1

In [8]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


In [10]:
matrix_3 = np.ones((10,10), dtype=int)
print(matrix_3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


Null Matrix or Zero Matrix

In [11]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [13]:
null_matrix = np.zeros((7,7),dtype=int)
print(null_matrix)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


Identity Matrix

In [14]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
identity_matrix = np.eye(5,5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Transpose of a Matrix

In [20]:
# matrix with random integer values
a = np.random.randint(100, size=(4,5))
print(a)

[[29  7 21 34 42]
 [67 58  3 23 71]
 [96 41 47 68 62]
 [42 37 85 43 87]]


In [21]:
transpose_of_a = np.transpose(a)
print(transpose_of_a)

[[29 67 96 42]
 [ 7 58 41 37]
 [21  3 47 85]
 [34 23 68 43]
 [42 71 62 87]]


**Matrix Addition**

Two Matrices can be added only if they have the same shape

In [22]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [23]:
print(A)

[[2 3]
 [4 5]]


In [24]:
print(B)

[[6 7]
 [8 9]]


In [25]:
A.shape

(2, 2)

In [26]:
B.shape

(2, 2)

Adding two Matrices

In [27]:
sum = A + B

In [28]:
print(sum)

[[ 8 10]
 [12 14]]


In [29]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [30]:
print(matrix_1)

[[8 8 4]
 [6 4 2]
 [0 0 9]]


In [31]:
print(matrix_2)

[[ 4  0 18]
 [11 19  4]
 [19  8  9]]


In [32]:
sum = np.add(matrix_1, matrix_2)

In [33]:
print(sum)

[[12  8 22]
 [17 23  6]
 [19  8 18]]


In [34]:
# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

In [35]:
sum_2 = np.add(matrix_3, matrix_4)

ValueError: ignored

We get this error because shape of matrix_3 and matrix_4 are different

**Matrix** **Subtraction**

In [36]:
# creating two matrices

A = np.array([[2,3],[4,5]])

B = np.array([[6,7],[8,9]])

In [37]:
print(A)

[[2 3]
 [4 5]]


In [38]:
print(B)

[[6 7]
 [8 9]]


In [39]:
difference = A - B

In [40]:
print(difference)

[[-4 -4]
 [-4 -4]]


In [41]:
# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

In [42]:
print(matrix_1)

[[0 7 0]
 [7 8 8]
 [3 1 1]]


In [43]:
print(matrix_2)

[[ 5  8  1]
 [ 5  9  9]
 [17 14 14]]


In [44]:
diff = np.subtract(matrix_1, matrix_2)

In [45]:
print(diff)

[[ -5  -1  -1]
 [  2  -1  -1]
 [-14 -13 -13]]


**Multiplying a matrix by a scalar**

In [46]:
x = 5
y = np.random.randint(10, size=(4,4))

print(y)

[[7 4 5 3]
 [8 1 9 5]
 [5 0 7 9]
 [5 9 5 8]]


In [47]:
product = np.multiply(x,y)

In [48]:
print(product)

[[35 20 25 15]
 [40  5 45 25]
 [25  0 35 45]
 [25 45 25 40]]


**Multiplying 2 Matrices**

In [49]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [50]:
print(matrix_3)

[[1 2 2]
 [2 3 0]
 [3 1 4]]


In [51]:
print(matrix_4)

[[1 3 1 3]
 [3 0 4 2]
 [1 3 2 3]]


In [52]:
product = np.dot(matrix_3, matrix_4)

In [53]:
print(product)

[[ 9  9 13 13]
 [11  6 14 12]
 [10 21 15 23]]


In [54]:
product.shape

(3, 4)

In [55]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(4,4))

In [56]:
product = np.dot(matrix_3, matrix_4)

ValueError: ignored

**Element wise Matrix Multiplication**

In [58]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,3))

In [59]:
print(matrix_3)

[[0 1 0]
 [0 1 1]
 [3 0 3]]


In [60]:
print(matrix_4)

[[1 0 2]
 [4 3 4]
 [4 4 4]]


In [61]:
product = np.multiply(matrix_3, matrix_4)

In [62]:
print(product)

[[ 0  0  0]
 [ 0  3  4]
 [12  0 12]]


In [63]:
# create two matrices with random values
matrix_3 = np.random.randint(5, size=(3,3))
matrix_4 = np.random.randint(5, size=(3,4))

In [64]:
product = np.multiply(matrix_3, matrix_4)

ValueError: ignored